backend:
  name: github
  repo: MediaPlay-Discord/website # Path to your GitHub repository
  # optional, defaults to master
  # branch: main

media_folder: static/assets
public_folder: /assets
collections:
  - name: "home"
    label: "Home"
    folder: "content"
    create: true
    slug: "{{slug}}"
    preview_path: /
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "studios"
    label: "Studios"
    folder: "content/studios"
    create: true
    slug: "{{slug}}"
    preview_path: /
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "community"
    label: "Community"
    folder: "content/community"
    create: true
    slug: "{{slug}}"
    preview_path: /
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "discord"
    label: "Community/Discord"
    folder: "content/community/discord"
    create: true
    slug: "{{slug}}"
    preview_path: /
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "applications"
    label: "Applications"
    folder: "content/applications"
    create: true
    slug: "{{slug}}"
    preview_path: /
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    preview_path: blog/{{slug}}
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Discord Profile", name: "discord", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
